//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OpenGL.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_HTML_SENSDIAG               103
#define IDR_HTML_SENSITIVITYDIALOG      104
#define IDR_HTML_SENSITIVITYDIALOG1     106
#define IDR_HTML_PERSPECTIVEDIALOG      107
#define IDR_MAINFRAME                   128
#define IDR_OPENGLTYPE                  129
#define IDD_LIGHTS_DLG                  134
#define IDD_MATERIAL_DLG                136
#define IDD_DIALOG1                     139
#define IDD_DIALOG2                     144
#define IDD_SENS_DLG                    144
#define IDD_DIALOG3                     147
#define IDD_RATIO_DLG                   147
#define IDD_MULTIVIEWS_DLG              149
#define IDD_FOG_DLG                     150
#define IDD_VECTOR_DLG                  152
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_MATERIAL_AMBIENT            1039
#define IDC_MATERIAL_DIFFUSE            1040
#define IDC_SCROLLBAR1                  1040
#define IDC_MATERIAL_SHININESS          1041
#define IDC_MATERIAL_SPECULAR           1042
#define IDC_EDIT2                       1047
#define IDC_EDIT1                       1049
#define IDC_EDIT_END                    1050
#define IDC_EDIT_L                      1052
#define IDC_SLIDER_DENS                 1053
#define IDC_SLIDER2                     1054
#define IDC_SLIDER_ALPHA                1054
#define IDC_EDIT_START                  1055
#define IDC_COMBO_QUALITY               1056
#define IDC_EDIT_R                      1057
#define IDC_COMBO_MODE                  1057
#define IDC_TEXT_X                      1057
#define IDC_EDIT_D                      1058
#define IDC_TEXT_Y                      1058
#define IDC_EDIT_B                      1059
#define IDC_TEXT_Z                      1059
#define IDC_EDIT_T                      1060
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_SPACE_OBJECT                 32784
#define ID_SPACE_SCREEN                 32785
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_OPTIONS_MOUSESENSITIVITY     32799
#define ID_VIEW_MODELVIEW               32801
#define ID_VIEW_CAMERAVIEW              32802
#define ID_Menu                         32803
#define ID_VIEW_VIEW1                   32804
#define ID_VIEW_VIEW2                   32805
#define ID_VIEW_VIEW3                   32806
#define ID_VIEW_VIEW4                   32807
#define ID_VIEW_MULTIPLEVIEWS           32811
#define ID_RESET_VIEW                   32813
#define ID_VIEW_POLYGONSNORMALS         32821
#define ID_VIEW_VERTICESNORMALS         32822
#define ID_VIEW_M                       32823
#define ID_VIEW_BOUNDING_BOX            32824
#define ID_ACTION_SETCOLOR              32825
#define ID_ACTION_SETBACKGROUNDCOLOR    32826
#define ID_ACTION_RESETCOLORS           32827
#define ID_VIEW_MULTIPLEOBJECTS         32828
#define ID_VIEW_OBJECT2                 32829
#define ID_Menu32830                    32830
#define ID_VIEW_WIREFRAME               32831
#define ID_FOG_SETPARAMETERS            32832
#define ID_VIEW_ENABLEFOG               32833
#define ID_VIEW_SETFOGPARAMETERS        32834
#define ID_MATERIAL_SETMATERIALPARAMETERS 32835
#define ID_VIEW_TESSELLATION            32836
#define ID_ACTION_SETFOGCOLOR           32837
#define ID_ACTION_USEMODELCOLORS        32838
#define ID_VIEW_CULLBACKFACES           32839
#define ID_ACTION_TEXTURETRANSFORMATION 32849
#define ID_MATERIAL_USEUTEXTURE         32850
#define ID_MATERIAL_USEVTEXTURE         32851
#define ID_Menu32852                    32852
#define ID_MATERIAL_USEVTEXTURE32853    32853
#define ID_MATERIAL_GENERATEUVECTOR     32854
#define ID_MATERIAL_GENERATEVVECTOR     32855
#define ID_MATERIAL_USESELFUOORDINATES  32856
#define ID_MATERIAL_C                   32857
#define ID_MATERIAL_USESELFUCOORDINATES 32858
#define ID_MATERIAL_USESELFVCOORDINATES 32859
#define ID_MATERIAL_USEMIPMAP           32860
#define ID_MATERIAL_UTEXTUREFILLING     32861
#define ID_UTEXTUREFILLING_REPEAT       32862
#define ID_UTEXTUREFILLING_CLAMP        32863
#define ID_UCOORDINATESSPACE_SCREENSPACE 32864
#define ID_UCOORDINATESSPACE_MODELSPACE 32865
#define ID_UCOORDINATESSPACE_SCREENSPACE32866 32866
#define ID_UCOORDINATESSPACE_MODELSPACE32867 32867
#define ID_MATERIAL_VTEXTUREFILLING     32868
#define ID_VTEXTUREFILLING_REPEAT       32869
#define ID_VTEXTUREFILLING_CLAMP        32870
#define ID_VCOORDINATESSPACE_SCREENSPACE 32871
#define ID_VCOORDINATESSPACE_MODELSPACE 32872
#define ID_Menu32873                    32873
#define ID_MATERIAL_SELECTOBJECTFORMIPMAPPING 32874
#define ID_MATERIAL_SELECTOBJECT        32875
#define ID_Menu32876                    32876
#define ID_FILE_LOADGLOBALTEXTURE       32877

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32878
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
