// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "scrollbar1.h"

/////////////////////////////////////////////////////////////////////////////
// CScrollbar1

IMPLEMENT_DYNCREATE(CScrollbar1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CScrollbar1 properties

/////////////////////////////////////////////////////////////////////////////
// CScrollbar1 operations
